In [26]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB, MultinomialNB, CategoricalNB, BernoulliNB
from sklearn.preprocessing import LabelEncoder
import pprint
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix

# To consider empty string and numpu.inf as NA values we use use below statement
pd.options.mode.use_inf_as_na = True

data = pd.read_excel('lab02_dataset_2.xlsx', engine='openpyxl')
data.head()

/var/folders/q3/91x5m0k55jz1bvt_fqnvcwn00000gn/T/ipykernel_32984/2746034254.py:10: FutureWarning: use_inf_as_na option is deprecated and will be removed in a future version. Convert inf values to NaN before operating instead.
  pd.options.mode.use_inf_as_na = True

,ID,KIDSDRIV,BIRTH,AGE,HOMEKIDS,YOJ,INCOME,PARENT1,HOME_VAL,MSTATUS,...,TIF,CAR_TYPE,RED_CAR,REVOKED,MVR_PTS,CAR_AGE,URBANICITY,CLM_AMT,CLM_COUNT,EXPOSURE
0,63581743,0,1939-03-16,60.0,0,11.0,67000.0,No,NaN,No,...,11,Minivan,yes,No,3,18.0,Highly Urban/ Urban,0,0,0.189
1,132761049,0,1956-01-21,43.0,0,11.0,91000.0,No,257000.0,No,...,1,Minivan,yes,No,0,1.0,Highly Urban/ Urban,0,0,1.000
2,921317019,0,1951-11-18,48.0,0,11.0,53000.0,No,NaN,No,...,1,Van,yes,No,2,10.0,Highly Urban/ Urban,0,0,1.000
3,727598473,0,1964-03-05,35.0,1,10.0,16000.0,No,124000.0,Yes,...,4,SUV,no,No,3,10.0,Highly Urban/ Urban,0,0,0.828
4,450221861,0,1948-06-05,51.0,0,14.0,NaN,No,306000.0,Yes,...,7,Minivan,yes,No,0,6.0,Highly Urban/ Urban,0,0,0.729

In [15]:
data = pd.DataFrame({
    'CAR_TYPE' : data['CAR_TYPE'],
    'OCCUPATION': data['OCCUPATION'],
    'EDUCATION': data['EDUCATION'],
    'CAR_USE': data['CAR_USE']
})
data.head()

  CAR_TYPE    OCCUPATION      EDUCATION     CAR_USE
0  Minivan  Professional            PhD     Private
1  Minivan   Blue Collar    High School  Commercial
2      Van       Manager      Bachelors     Private
3      SUV      Clerical    High School     Private
4  Minivan   Blue Collar  Below High Sc     Private

In [16]:
# checking if any of the column has null values
data[['CAR_TYPE', 'OCCUPATION', 'EDUCATION', 'CAR_USE']].isna().any()

CAR_TYPE      False
OCCUPATION    False
EDUCATION     False
CAR_USE       False
dtype: bool

In [17]:
data[['CAR_TYPE', 'OCCUPATION', 'EDUCATION', 'CAR_USE']].isnull().any()

CAR_TYPE      False
OCCUPATION    False
EDUCATION     False
CAR_USE       False
dtype: bool

In [18]:
data.dropna(subset=['CAR_TYPE', 'OCCUPATION', 'EDUCATION', 'CAR_USE'], how='all', inplace=True)

In [19]:
data.shape

(10302, 4)

In [20]:
data[['CAR_TYPE', 'OCCUPATION', 'EDUCATION', 'CAR_USE']]

          CAR_TYPE    OCCUPATION      EDUCATION     CAR_USE
0          Minivan  Professional            PhD     Private
1          Minivan   Blue Collar    High School  Commercial
2              Van       Manager      Bachelors     Private
3              SUV      Clerical    High School     Private
4          Minivan   Blue Collar  Below High Sc     Private
...            ...           ...            ...         ...
10297      Minivan       Manager            PhD     Private
10298  Panel Truck       Unknown        Masters  Commercial
10299          SUV   Blue Collar  Below High Sc     Private
10300      Minivan    Home Maker      Bachelors     Private
10301      Minivan      Clerical    High School     Private

[10302 rows x 4 columns]

In [21]:
features = ['CAR_TYPE', 'OCCUPATION', 'EDUCATION', 'CAR_USE']
featureDict = dict()
for col in features:
    encoder = LabelEncoder()
    data[col] = encoder.fit_transform(data[col])
    print(list(encoder.classes_))
    label_mappings = encoder.classes_

# Private = 1
# Commercial = 0
    labelDict={}
    for i, label in enumerate(label_mappings):
        # print(i , " -> ", label)
        labelDict[label] = i
    
    featureDict[col] = labelDict

pprint.pprint(featureDict)

['Minivan', 'Panel Truck', 'Pickup', 'SUV', 'Sports Car', 'Van']
['Blue Collar', 'Clerical', 'Doctor', 'Home Maker', 'Lawyer', 'Manager', 'Professional', 'Student', 'Unknown']
['Bachelors', 'Below High Sc', 'High School', 'Masters', 'PhD']
['Commercial', 'Private']
{'CAR_TYPE': {'Minivan': 0,
              'Panel Truck': 1,
              'Pickup': 2,
              'SUV': 3,
              'Sports Car': 4,
              'Van': 5},
 'CAR_USE': {'Commercial': 0, 'Private': 1},
 'EDUCATION': {'Bachelors': 0,
               'Below High Sc': 1,
               'High School': 2,
               'Masters': 3,
               'PhD': 4},
 'OCCUPATION': {'Blue Collar': 0,
                'Clerical': 1,
                'Doctor': 2,
                'Home Maker': 3,
                'Lawyer': 4,
                'Manager': 5,
                'Professional': 6,
                'Student': 7,
                'Unknown': 8}}

In [22]:
data.head()

   CAR_TYPE  OCCUPATION  EDUCATION  CAR_USE
0         0           6          4        1
1         0           0          2        0
2         5           5          0        1
3         3           1          2        1
4         0           0          1        1

In [23]:
X = data[['CAR_TYPE', 'OCCUPATION', 'EDUCATION']]
Y = data[['CAR_USE']]

In [24]:
X.head()

   CAR_TYPE  OCCUPATION  EDUCATION
0         0           6          4
1         0           0          2
2         5           5          0
3         3           1          2
4         0           0          1

In [25]:
Y.head()

   CAR_USE
0        1
1        0
2        1
3        1
4        1

In [29]:
model = BernoulliNB(alpha=0.01)
model.fit(X, Y)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/utils/validation.py:1229: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

BernoulliNB(alpha=0.01)

In [31]:
class_probs = model.predict_proba(np.ones([1, X.shape[1]]))[:, 1]  # Assuming binary classes
print("Class Probabilities (P(Yj))")
print(class_probs)

Class Probabilities (P(Yj))
[0.71369068]

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(